#!/usr/bin/env python3
"""Rewrite the moon strip of pbl_assumptions_pyramid.tex from its \moon entries and block positions."""
import re, pathlib, sys
P = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path("pbl_assumptions_pyramid.tex"); s = P.read_text()
nc = "\n".join(l for l in s.splitlines() if not l.lstrip().startswith("%"))
def take_args(t, i, n):
    args = []
    for _ in range(n):
        assert t[i] == "{"; d = 0; j = i
        while True:
            if t[j] == "{": d += 1
            elif t[j] == "}":
                d -= 1
                if d == 0: break
            j += 1
        args.append(t[i+1:j]); i = j + 1
    return args, i
t0 = s.index("\\begin{tikzpicture}"); t1 = s.index("\\end{tikzpicture}"); body = s[t0:t1]
blocks = {}
for m in re.finditer(r"\\(pbf|pb)\{", body):
    args, _ = take_args(body, m.end() - 1, 7 if m.group(1) == "pbf" else 6)
    title = re.match(r"\\textbf\{(.*?)\}\\\\", args[5] + "\\\\").group(1)
    blocks[title] = (float(args[0]), float(args[1]), float(args[2]), float(args[3]), args[4])
moons = {}
for m in re.finditer(r"\\moon\{", nc):
    (title, vals), _ = take_args(nc, m.end() - 1, 2); moons[title] = vals.split()
ytop = max(b[3] for b in blocks.values())
rows = [("cMYNN", 0.35), ("cGXIX", 0.70), ("cAPPROX", 1.05), ("cFULL", 1.40)]
glyph = {"K": "\\gK", "P": "\\gP", "D": "\\gD"}
out = ["% ---- moons: scheme quicklook (GENERATED by scripts/make_moons.py; do not edit by hand) ----",
       f"\\node[tier] at (-0.3, {ytop + 0.875:.3f}) {{schemes}};"]
for title, vals in moons.items():
    if title not in blocks: sys.exit(f"unknown block in \\moon: {title!r}")
    x0, x1 = blocks[title][0], blocks[title][1]; xc = (x0 + x1) / 2
    for (col, dy), v in zip(rows, vals):
        out.append(f"\\node[inner sep=0pt] at ({xc:.3f},{ytop + dy:.2f}) {{\\color{{{col}}}{glyph[v]}}};")
out.append("% ---- end moons ----")
i0 = s.index("% ---- moons: scheme quicklook"); i1 = s.index("% ---- end moons ----") + len("% ---- end moons ----")
s = s[:i0] + "\n".join(out) + s[i1:]
P.write_text(s); print("moons:", len(moons), "blocks x", len(rows), "rows")
