#!/usr/bin/env python3
"""Figure variant of the colour-coded pyramid for the PhD concept (Elias, 2026-09-29): the picture only, as big as the
page allows, with the legend INSIDE the figure so the caption can stay one line.

  * reads the GENERATED colour page (default pbl_assumptions_pyramid_split_vertical_colour.tex; run
    make_pyramid_vertical.py and make_pyramid_colour.py first) and writes pbl_assumptions_pyramid_concept.tex;
  * standalone class, only the tikzpicture: title, legend paragraph and page 2 are dropped;
  * the "schemes" column header becomes four rotated labels in the scheme colours above the moon columns;
  * a three-line key above the column headers: blocks and tabs, corner marks, moons.
Usage: python3 scripts/make_pyramid_concept.py [COLOUR.tex]  ->  tectonic pbl_assumptions_pyramid_concept.tex
       then copy the PDF to phd_concept/figures/pbl_assumptions_pyramid.pdf.
"""
import re, sys, pathlib

SRC = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path("pbl_assumptions_pyramid_split_vertical_colour.tex")
DST = SRC.with_name("pbl_assumptions_pyramid_concept.tex")
MOON_X = (18.450, 18.790, 19.130, 19.470)          # moon columns, MYNN as run, G19 port, 3D-APPROX, 3D-FULL
SCHEMES = (("cMYNN", "MYNN"), ("cGXIX", "G19"), ("cAPPROX", "3D-APPROX"), ("cFULL", "3D-FULL"))

s = SRC.read_text()
pre, body = s.split("\\begin{document}", 1)
pre = pre.replace("\\documentclass[10pt]{article}", "\\documentclass[10pt,border=1mm]{standalone}")
pre = re.sub(r"^\\usepackage\[a4paper[^\n]*\n", "", pre, flags=re.M)
if "cAPPROX" not in pre:
    pre = pre.replace("\\definecolor{cFULL}", "\\definecolor{cAPPROX}{HTML}{9A5AA8}\\definecolor{cMYNN}{HTML}{3A6B00}\n\\definecolor{cFULL}", 1)
a = body.index("\\begin{tikzpicture}")
b = body.index("\\end{tikzpicture}") + len("\\end{tikzpicture}")
pic = body[a:b]

# scheme labels instead of the "schemes" header
pic = re.sub(r"\\node\[font=\\scriptsize\\bfseries, text=black!60\] at \(18\.960,23\.871\) \{schemes\};\n",
             lambda m: "".join(f"\\node[font=\\fontsize{{5}}{{5.5}}\\selectfont\\bfseries, text={c}, rotate=90, anchor=west] "
                     f"at ({x:.3f},23.55) {{{n}}};\n" for x, (c, n) in zip(MOON_X, SCHEMES)), pic)
assert "{MYNN}" in pic, "schemes header not found"

key = r"""
% ---- key (concept variant): read the figure without the caption
\node[anchor=south west, inner sep=0pt, text width=19.6cm, font=\fontsize{6}{7.2}\selectfont, align=left] at (0,24.55) {%
\textbf{Block}: one assumption a scheme makes in order to run; it touches at its left exactly the blocks it rests on.
\textbf{Tab}: shortcut, P premises, C concepts, F formal statements of the level-2.5 closure, numbered from the top.\\
\textbf{Corner mark}: a dependence no contact can show, in the colour and with the tab of the block depended on
(triangle: previous column; arrowhead: same column, up or down; thick border: load-bearing).
\textbf{Colour} names a place: hue by height, shade by column.\\
\textbf{Moons}, per formal statement, left to right \textcolor{cMYNN}{\textbf{MYNN}}, \textcolor{cGXIX}{\textbf{G19}},
\textcolor{cAPPROX}{\textbf{3D-APPROX}}, \textcolor{cFULL}{\textbf{3D-FULL}}:
\tikz[baseline=-0.6ex]{\fill (0,0) circle (0.09);}~kept,
\tikz[baseline=-0.6ex]{\draw[line width=0.4pt] (0,0) circle (0.09); \fill (0,0) -- (90:0.09) arc (90:270:0.09) -- cycle;}~partly,
\tikz[baseline=-0.6ex]{\draw[line width=0.4pt] (0,0) circle (0.09);}~dropped.
\textbf{Dashed boxes}: what breaks in hectometre-scale simulations over complex terrain.};
"""
pic = pic.replace("\\end{tikzpicture}", key + "\\end{tikzpicture}")
DST.write_text("% GENERATED by scripts/make_pyramid_concept.py from " + SRC.name + " -- do not edit.\n"
               + pre + "\\begin{document}\n" + pic + "\n\\end{document}\n")
print("wrote", DST)
