#!/bin/bash
# Build a ready-to-submit WRF run directory for the ICON-forced Inn Valley case.
#
#   realcase/scripts/setup_rundir.sh <envfile> <rundir> <pbl3d|mynn> \
#        --geo /path/to/geo_em_d01.nc --met-dir /path/to/met_em [--hours N] [--smoke]
#
# It links the run/ tables and the executables, links the met_em files, drops in
# the right namelist, syncs the WPS-derived values into it with
# prepare_namelist.py, and copies the SLURM scripts.  Nothing is copied that
# would go stale: tables and executables are symlinks back into the source tree,
# so a rebuild is picked up without redoing the run directory.
#
#   --hours N   run length in hours (default: whatever the met_em files cover)
#   --smoke     1 h run, output every 10 min -- use this first to measure
#               throughput and confirm stability before queueing the full day
set -u -o pipefail

usage() { sed -n '2,18p' "$0"; exit 1; }
[ $# -ge 3 ] || usage

ENVFILE=$1; RUNDIR=$2; CONFIG=$3; shift 3
GEO=""; METDIR=""; HOURS=""; SMOKE=0
while [ $# -gt 0 ]; do
  case "$1" in
    --geo)     GEO=$2; shift 2 ;;
    --met-dir) METDIR=$2; shift 2 ;;
    --hours)   HOURS=$2; shift 2 ;;
    --smoke)   SMOKE=1; shift ;;
    -h|--help) usage ;;
    *) echo "unknown argument: $1" >&2; usage ;;
  esac
done

case "$CONFIG" in pbl3d|mynn) ;; *) echo "config must be pbl3d or mynn" >&2; exit 1 ;; esac

HERE=$(cd "$(dirname "$0")" && pwd)
RC=$(cd "$HERE/.." && pwd)
WRF=$(cd "$RC/.." && pwd)
[ -f "$ENVFILE" ] || ENVFILE="$RC/$ENVFILE"
[ -f "$ENVFILE" ] || { echo "env file not found: $ENVFILE" >&2; exit 1; }
# Resolve to an absolute path -- env.sh below embeds this string verbatim,
# and it gets sourced from inside $RUNDIR (a different cwd), so a relative
# path here would silently fail to source at job-launch time.
ENVFILE=$(cd "$(dirname "$ENVFILE")" && pwd)/$(basename "$ENVFILE")
# shellcheck disable=SC1090
. "$ENVFILE"

for exe in real.exe wrf.exe; do
  [ -x "$WRF/main/$exe" ] || { echo "$WRF/main/$exe is missing -- run build_em_real.sh first" >&2; exit 1; }
done

mkdir -p "$RUNDIR" || exit 1
RUNDIR=$(cd "$RUNDIR" && pwd)
echo "=== run directory: $RUNDIR"

# --- static tables and executables -----------------------------------------
echo "=== linking tables from $WRF/run"
n=0
for f in "$WRF"/run/*; do
  b=$(basename "$f")
  case "$b" in
    *.exe|namelist.*|README*) continue ;;
  esac
  ln -sfn "$f" "$RUNDIR/$b" && n=$((n + 1))
done
echo "    $n files"
for exe in real.exe wrf.exe ndown.exe tc.exe; do
  [ -e "$WRF/main/$exe" ] && ln -sfn "$WRF/main/$exe" "$RUNDIR/$exe"
done
ln -sfn "$RC/iofields.txt" "$RUNDIR/iofields.txt"

# --- met_em ----------------------------------------------------------------
if [ -n "$METDIR" ]; then
  echo "=== linking met_em from $METDIR"
  m=0
  for f in "$METDIR"/met_em.d01.*.nc; do
    [ -e "$f" ] || continue
    ln -sfn "$f" "$RUNDIR/$(basename "$f")" && m=$((m + 1))
  done
  [ "$m" -gt 0 ] || { echo "!!! no met_em.d01.*.nc in $METDIR" >&2; exit 1; }
  echo "    $m files"
else
  echo "=== no --met-dir given; link met_em.d01.*.nc into $RUNDIR yourself"
fi

# --- namelist --------------------------------------------------------------
echo "=== namelist: realcase/namelist.input.$CONFIG"
cp "$RC/namelist.input.$CONFIG" "$RUNDIR/namelist.input"

SYNC=("$RC/scripts/prepare_namelist.py" "$RUNDIR/namelist.input" --apply)
[ -n "$GEO" ]    && SYNC+=(--geo "$GEO")
[ -n "$METDIR" ] && SYNC+=(--met-dir "$METDIR")
[ -n "$HOURS" ]  && SYNC+=(--hours "$HOURS")
if [ "$SMOKE" = 1 ]; then
  echo "=== smoke mode: 1 h, output every 10 min"
  SYNC+=(--smoke)
fi
echo "=== syncing the namelist to geo_em/met_em"
python3 "${SYNC[@]}"
SYNC_RC=$?

# --- SLURM -----------------------------------------------------------------
cp "$RC/scripts/submit_real.slurm" "$RC/scripts/submit_wrf.slurm" "$RUNDIR/"
printf '%s\n' "$ENVFILE" > "$RUNDIR/.wrfenv"
cat > "$RUNDIR/env.sh" <<EOF
# generated by setup_rundir.sh -- sourced by the SLURM scripts
. "$ENVFILE"
export WRF_SRC="$WRF"
EOF

echo
echo "=== $RUNDIR is set up ($CONFIG)"
if [ "$SYNC_RC" != 0 ]; then
  echo "!!! prepare_namelist.py reported FATAL findings above -- fix them first"
  exit 1
fi
cat <<EOF

Next, in $RUNDIR:
    1. edit the #SBATCH header of submit_real.slurm / submit_wrf.slurm
       (account, partition, node count -- they ship with placeholders)
    2. sbatch submit_real.slurm
    3. python3 $RC/scripts/check_wrfinput.py wrfinput_d01
       -- do read this one, especially the SMOIS range
    4. sbatch submit_wrf.slurm
EOF
