#!/bin/bash
# Build a restart-based diagnosis/continuation run dir on the SAME MPI layout
# (2 nodes x 128) as the reference runs, starting from an existing wrfrst file
# instead of cold from met_em. Packages what A12, A13, X6r and F1..F3 all did
# by hand on 2026-08-21.
#
# Why a restart: re-entering just before an event on the same decomposition
# reproduces it bit-faithfully -- this configuration is NOT bit-reproducible
# across decompositions or after any last-bit change (KNOWN_ISSUES E14). A
# restart that adds an output stream needs override_restart_timers=.true. or
# the new stream never opens (KNOWN_ISSUES E17). auxhist24_interval_m must
# never be 0 -- that aborts the run at start, not just the stream
# (KNOWN_ISSUES E15).
#
# Usage:
#   setup_restart_run.sh <NAME> --rst <wrfrst file> --start HH[:MM] --hours H \
#       [--minutes M] [--stream23-min N] [--stream23-begin-min N] \
#       [--iofields FILE] [--history-min N] [--wrflux-min N] \
#       [--set key=value ...] [--nodes N] [--time HH:MM:SS] [--qos devel] [--partition P] \
#       [--submit]
#
# Examples:
#   # A13: 12-min devel-QOS smoke test of the 07:00 restart, 1-min q^2 budget
#   setup_restart_run.sh A13 \
#       --rst /gpfs/data/fs72996/ewahl/branko_runs/innval_pbl3d_X6/wrfrst_d01_2025-07-18_07:00:00 \
#       --start 07 --hours 0 --minutes 12 --stream23-min 1 \
#       --iofields realcase/iofields_a13.txt --history-min 5 --qos devel --nodes 5
#
#   # F1: 3.5 h fog/cold-air diagnosis, 5-min q^2 budget, 30-min WRFlux budgets
#   setup_restart_run.sh F1 --start 04 --hours 3 --minutes 30 \
#       --stream23-min 5 --wrflux-min 30 --iofields realcase/iofields_fog.txt \
#       --set icloud=0
set -u -o pipefail

DATA=/gpfs/data/fs72996/ewahl
HERE=$(cd "$(dirname "$0")" && pwd)
RC=$(cd "$HERE/.." && pwd)
BRANKO=$(cd "$RC/.." && pwd)
WRFINPUT_SRC=$DATA/branko_runs/innval_pbl3d_18th

usage() { sed -n '2,32p' "$0"; exit 1; }
[ $# -ge 1 ] || usage
NAME=$1; shift
[[ "$NAME" =~ ^[A-Za-z0-9_]+$ ]] || { echo "NAME must be alnum/underscore: $NAME" >&2; exit 1; }

RST=""; START=""; HOURS=""; MINUTES=0; S23MIN=""; S23BEGIN=""
IOFIELDS=""; HISTMIN=30; WRFLUXMIN=360; NODES=2; WTIME="03:00:00"; QOS=""; PART=""
SUBMIT=0
declare -a SETS=()
while [ $# -gt 0 ]; do
  case "$1" in
    --rst) RST=$2; shift 2 ;;
    --start) START=$2; shift 2 ;;
    --hours) HOURS=$2; shift 2 ;;
    --minutes) MINUTES=$2; shift 2 ;;
    --stream23-min) S23MIN=$2; shift 2 ;;
    --stream23-begin-min) S23BEGIN=$2; shift 2 ;;
    --iofields) IOFIELDS=$2; shift 2 ;;
    --history-min) HISTMIN=$2; shift 2 ;;
    --wrflux-min) WRFLUXMIN=$2; shift 2 ;;
    --set) SETS+=("$2"); shift 2 ;;
    --nodes) NODES=$2; shift 2 ;;
    --time) WTIME=$2; shift 2 ;;
    --qos) QOS=$2; shift 2 ;;
    --partition) PART=$2; shift 2 ;;   # lane (zen3_0512|zen3_1024|zen3_2048); QOS follows unless --qos devel (2026-08-28)
    --submit) SUBMIT=1; shift ;;
    -h|--help) usage ;;
    *) echo "unknown argument: $1" >&2; usage ;;
  esac
done
[ -n "$RST" ]   || { echo "--rst is required" >&2; exit 1; }
[ -n "$START" ] || { echo "--start is required" >&2; exit 1; }
[ -n "$HOURS" ] || { echo "--hours is required" >&2; exit 1; }
RST=$(readlink -f "$RST") || exit 1
[ -f "$RST" ] || { echo "no such restart file: $RST" >&2; exit 1; }

# split HH[:MM]
START_H=${START%%:*}
START_M=0; [[ "$START" == *:* ]] && START_M=${START#*:}
START_H=$((10#$START_H)); START_M=$((10#$START_M))

RUNDIR=$DATA/branko_runs/innval_pbl3d_$NAME
ENV=$RC/env/vsc5_$NAME.sh

echo "=== env file: $ENV"
if [ -f "$ENV" ]; then
  echo "    already exists, left alone"
else
  cat > "$ENV" <<EOF
#!/bin/bash
# $NAME: restart-based run, generated by setup_restart_run.sh.
source "\$(dirname "\${BASH_SOURCE[0]}")/vsc5.sh"
export WRF_OUTPUT_ROOT=$DATA/exp/$NAME
EOF
  echo "    written"
fi

[ -x "$BRANKO/main/wrf.exe" ] || { echo "!!! $BRANKO/main/wrf.exe missing -- build first" >&2; exit 1; }

echo "=== setup_rundir.sh $RUNDIR"
"$RC/scripts/setup_rundir.sh" "$ENV" "$RUNDIR" pbl3d \
    --met-dir "$DATA/WPS/metgrid_output" --hours 6 || exit 1

echo "=== re-linking wrfinput_d01/wrfbdy_d01 from $WRFINPUT_SRC, restart file, iofields"
ln -sfn "$WRFINPUT_SRC/wrfinput_d01" "$RUNDIR/wrfinput_d01"
ln -sfn "$WRFINPUT_SRC/wrfbdy_d01"   "$RUNDIR/wrfbdy_d01"
ln -sfn "$RST" "$RUNDIR/$(basename "$RST")"

IOF_BASENAME=iofields_lscale.txt
if [ -n "$IOFIELDS" ]; then
  IOFIELDS=$(readlink -f "$IOFIELDS") || exit 1
  [ -f "$IOFIELDS" ] || { echo "no such iofields file: $IOFIELDS" >&2; exit 1; }
  IOF_BASENAME=$(basename "$IOFIELDS")
  ln -sfn "$IOFIELDS" "$RUNDIR/$IOF_BASENAME"
else
  # The namelist below points at the default file, so it must be in the run
  # dir; without this link WRF emits "Problem opening iofields_lscale.txt"
  # per rank and the file's -: removals silently never apply (X9a/X9b ran
  # with full-width frames that way).
  ln -sfn "$RC/iofields_lscale.txt" "$RUNDIR/$IOF_BASENAME"
fi

NL=$RUNDIR/namelist.input

# --- time window: same day, roll end_day forward if start+duration crosses midnight
END_MIN_TOTAL=$((START_H * 60 + START_M + HOURS * 60 + MINUTES))
END_DAY_ROLL=$((END_MIN_TOTAL / 1440))
END_MIN_TOTAL=$((END_MIN_TOTAL % 1440))
END_H=$((END_MIN_TOTAL / 60)); END_M=$((END_MIN_TOTAL % 60))
START_DAY=$(grep -m1 '^ start_day' "$NL" | sed -E "s/^[^=]*=\s*([0-9]+).*/\1/")
END_DAY=$((10#$START_DAY + END_DAY_ROLL))
[ "$END_DAY_ROLL" = 0 ] || echo "    note: run crosses midnight, end_day bumped to $END_DAY"

sedset() {
  # sedset KEY VALUE -- matches "^ key *=", fails loudly if the key is not there
  local key=$1 val=$2
  grep -qE "^ $key[[:space:]]*=" "$NL" || { echo "!!! namelist key not found: $key" >&2; exit 1; }
  sed -i -E "s/^( $key[[:space:]]*=[[:space:]]*)[^,!]*(,?)/\1$val\2/" "$NL"
}

sedset restart ".true."
sedset start_hour "$(printf '%02d' "$START_H")"
[ "$START_M" != 0 ] && sedset start_minute "$(printf '%02d' "$START_M")"
sedset run_days 0
sedset run_hours "$HOURS"
sedset run_minutes "$MINUTES"
sedset end_day "$(printf '%02d' "$END_DAY")"
sedset end_hour "$(printf '%02d' "$END_H")"
sedset end_minute "$(printf '%02d' "$END_M")"

RESTART_INTERVAL=0
for kv in "${SETS[@]}"; do
  [ "${kv%%=*}" = "restart_interval" ] && RESTART_INTERVAL=${kv#*=}
done
sedset restart_interval "$RESTART_INTERVAL"

if ! grep -q '^ override_restart_timers' "$NL"; then
  sed -i "/^ restart_interval[[:space:]]*=/a\\ override_restart_timers = .true.," "$NL"
  echo "    override_restart_timers = .true. inserted (KNOWN_ISSUES E17)"
fi

sedset iofields_filename "\"$IOF_BASENAME\""
sedset history_interval "$HISTMIN"
[ "$WRFLUXMIN" != 0 ] || { echo "!!! --wrflux-min 0 would abort at start (KNOWN_ISSUES E15)" >&2; exit 1; }
sedset auxhist24_interval_m "$WRFLUXMIN"

if [ -n "$S23MIN" ]; then
  echo "=== q^2 budget stream (auxhist23): $S23MIN-min frames"
  python3 "$RC/scripts/add_qsq_diag.py" "$NL" "$DATA/exp/$NAME" || exit 1
  # add_qsq_diag.py always points iofields_filename at iofields_qsq.txt; the
  # custom file passed via --iofields already carries the same stream-23
  # fields (see iofields_a13.txt/iofields_fog.txt), so restore it as the
  # authoritative choice.
  sedset iofields_filename "\"$IOF_BASENAME\""
  sedset auxhist23_interval_m "$S23MIN"
  if [ -n "$S23BEGIN" ]; then
    if grep -q '^ auxhist23_begin_m' "$NL"; then
      sedset auxhist23_begin_m "$S23BEGIN"
    else
      sed -i "/^ auxhist23_interval_m[[:space:]]*=/a\\ auxhist23_begin_m      = $S23BEGIN," "$NL"
    fi
  fi
fi

for kv in "${SETS[@]}"; do
  key=${kv%%=*}; val=${kv#*=}
  [ "$key" = "restart_interval" ] && continue   # already applied above
  sedset "$key" "$val"
done

# --- SLURM ------------------------------------------------------------------
SB=$RUNDIR/submit_wrf.slurm
sed -i -E "s/^#SBATCH --job-name=.*/#SBATCH --job-name=wrf_$NAME/" "$SB"
sed -i -E "s/^#SBATCH --nodes=.*/#SBATCH --nodes=$NODES/" "$SB"
sed -i -E "s/^#SBATCH --time=.*/#SBATCH --time=$WTIME/" "$SB"
grep -q -E '^#SBATCH --hint=nomultithread' "$SB" || sed -i "/^#SBATCH --ntasks-per-node=/a #SBATCH --hint=nomultithread" "$SB"   # anchored: the template's MUSICA comment also contains the string (KNOWN_ISSUES E25)
if [ "$QOS" = "devel" ]; then
  sed -i -E "s/^#SBATCH --qos=.*/#SBATCH --qos=zen3_0512_devel/" "$SB"
  sed -i -E "s/^#SBATCH --time=.*/#SBATCH --time=00:10:00/" "$SB"
fi
if [ -n "$PART" ]; then
  sed -i -E "s/^#SBATCH --partition=.*/#SBATCH --partition=$PART/" "$SB"
  [ "$QOS" = "devel" ] || sed -i -E "s/^#SBATCH --qos=.*/#SBATCH --qos=$PART/" "$SB"
fi

# --- report ------------------------------------------------------------------
echo; echo "=== final namelist values"
for key in restart start_year start_month start_day start_hour start_minute \
           run_days run_hours run_minutes end_day end_hour end_minute \
           restart_interval override_restart_timers iofields_filename \
           history_interval auxhist24_interval_m auxhist23_interval_m auxhist23_begin_m; do
  grep -E "^ $key[[:space:]]*=" "$NL"
done
for kv in "${SETS[@]}"; do grep -E "^ ${kv%%=*}[[:space:]]*=" "$NL"; done

echo; echo "=== SBATCH header"; grep -E '^#SBATCH' "$SB"

echo; echo "=== dangling symlinks (KNOWN_ISSUES E11)"
DANGLING=$(find "$RUNDIR" -maxdepth 1 -xtype l 2>/dev/null)
if [ -n "$DANGLING" ]; then
  echo "!!! dangling symlinks -- refusing to submit:"
  printf '%s\n' "$DANGLING" | sed 's/^/    /'
  SUBMIT=0; DANGLE_FAIL=1
else
  echo "    none"
fi

echo; echo "=== prepare_namelist.py re-validation (report only)"
OUTROOT=$(bash -c "source '$ENV' >/dev/null 2>&1; echo \$WRF_OUTPUT_ROOT")
python3 "$RC/scripts/prepare_namelist.py" "$NL" --output-root "$OUTROOT" 2>&1 | grep -E "FATAL|WARN"

[ "${DANGLE_FAIL:-0}" = 1 ] && { echo "!!! not submitting: dangling symlinks above" >&2; exit 1; }

echo
if [ "$SUBMIT" = 1 ]; then
  echo "=== submitting"; (cd "$RUNDIR" && sbatch submit_wrf.slurm)
else
  echo "cd $RUNDIR && sbatch submit_wrf.slurm"
fi
